INSERT INTO isogjdb.city (name) VALUES ('Minsk');
INSERT INTO isogjdb.city (name) VALUES ('Brest');
INSERT INTO isogjdb.type_of_accepted (name) VALUES ('Accept');
INSERT INTO isogjdb.type_of_accepted (name)  VALUES ('Not');
INSERT INTO isogjdb.type_of_education (name) VALUES ('High education');
INSERT INTO isogjdb.type_of_education (name)  VALUES ('School education');
INSERT INTO isogjdb.type_of_skil (name) VALUES  ('Practical');
INSERT INTO isogjdb.type_of_skill (name)  VALUES ('Theoretical');
INSERT INTO isogjdb.type_of_task (name) VALUES ('Sum type of task');
INSERT INTO isogjdb.type_of_user (name)  VALUES ('User');
INSERT INTO isogjdb.type_of_user (name) VALUES ('Company');
INSERT INTO isogjdb.type_of_user (name)  VALUES ('Admin');
INSERT INTO isogjdb.type_of_vacancy (name)  VALUES ('Dba');
INSERT INTO isogjdb.type_of_vacancy (name) VALUES ('Frontend');
INSERT INTO isogjdb.company (date_of_creation, info, name, city_of_company) VALUES ('2014-11-14 16:30:18', 'Bsuir company', 'Bsuir', 1);
INSERT INTO isogjdb.gender (name) VALUES ('Male');
INSERT INTO isogjdb.gender (name) VALUES ('Female');
INSERT INTO isogjdb.position (name) VALUES ('Junior');
INSERT INTO isogjdb.position (name) VALUES ('Senior');
INSERT INTO isogjdb.position (name) VALUES ('Middle');
INSERT INTO isogjdb.position (name) VALUES ('Expert');
INSERT INTO isogjdb.school (name, city) VALUES ('Number 6', 1);
INSERT INTO isogjdb.skill (name, type_of_skill) VALUES ('Model', 2);
INSERT INTO isogjdb.task (info, name, type_of_task) VALUES ('Do frontend', 'Front', 1);
INSERT INTO isogjdb.university (name, city) VALUES ('BSUIR', 1);
INSERT INTO isogjdb.faculty (name, university) VALUES ('Poit', 1);
INSERT INTO isogjdb.user (active, email, first_name, second_name, last_name, city_of_living, gender, type_of_user) VALUES (1, 'Vad@bsuir.by', 'Vadim', 'Mikalaevich', 'Vidnichuk', 1, 1, 3);
INSERT INTO isogjdb.user (active, email, first_name, second_name, last_name, city_of_living, gender, type_of_user) VALUES (1, 'User@Bsuir.by', 'User', 'Userovich', 'Userchuk', 1, 1, 1);
INSERT INTO isogjdb.user (active, email, first_name, second_name, last_name, city_of_living, gender, type_of_user) VALUES (1, 'Company', 'Company', 'Company', 'Company', 1, 1, 2);
INSERT INTO isogjdb.user_city_to_work (city, user) VALUES (1, 1);
INSERT INTO isogjdb.user_company (company, position, user) VALUES (1, 1, 1);
INSERT INTO isogjdb.user_skill (skill_mark, skill_practical_mark, id_marker, id_skill, id_user) VALUES ('6', '7', 2, 1, 1);
INSERT INTO isogjdb.vacancy (info_of_vacancy, task, type_of_vacancy, company) VALUES ('Do work', 1, 1, 1);
INSERT INTO isogjdb.vacancy_skill (skill, vacancy) VALUES (1, 1);
INSERT INTO isogjdb.vacancy_user (if_user_accepted, if_company_accepted, user, vacancy) VALUES (2, 2, 1, 1);
INSERT INTO isogjdb.education (end_of_education, start_of_education, faculty, school, type_of_education, user) VALUES ('2014-11-14 16:38:39', '2017-11-14 16:38:42', 1, null, 1, 1);
INSERT INTO isogjdb.experience (date_of_end, date_of_start, prev_company, user) VALUES ('2015-11-14 16:39:36', '2017-11-14 16:39:38', 1, 1);
INSERT INTO isogjdb.summary (text_of_summary, user) VALUES ('Good user summary', 1);