
spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    isogj:
      host: ${MYSQL_HOST:isogj-mysql}
      port: ${MYSQL_PORT:3306}
      current_schema: isogjdb
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.isogj.host}:${spring.datasource.isogj.port}/${spring.datasource.isogj.current_schema}?autoReconnect=true&useSSL=false
    username: root
    password:
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
    platform: mysql
  mvc.view:
    prefix: /templates/
    suffix: .html
  session:
    store-type: hash_map
    jdbc:
      initializer.enabled: true
      table-name: SPRING_SESSION
  http.multipart:
    enabled: true
    max-file-size: 100mb
    max-request-size: 100mb

spring.thymeleaf.cache: false


server.session.cookie.max-age: 3600
server.session.timeout: 60


logging.level:
  org.springframework.security: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring.queries.users-query: select email, user_password, active from user where email=?
spring.queries.roles-query: select u.email, r.role from user u inner join user_role ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?

flyway:
  schemas: ${spring.datasource.isogj.current_schema}
  url: jdbc:mysql://${spring.datasource.isogj.host}:${spring.datasource.isogj.port}/?autoReconnect=true&useSSL=false
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  enabled: true


ololo:
  lo: ${JAVA_HOME}
